### ISSUE TITLE
"Bad passphrase" while creating the instance

### ISSUE THREAD

**Issue by Eirikr70** [vsellier/easy-cozy#13]
So, here is my problem:
I have installed the container behind an nginx reverse proxy through the following `docker-compose.yml`
```
version: '3.0'

services:
  db:
    image: treehouses/rpi-couchdb:2.3.0
    container_name: db
    volumes:
      - ${DATABASE_DIRECTORY}:/opt/couchdb/data
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped

  cozy:
    image: vsellier/easy-cozy:${COZY_STACK_VERSION}
    container_name: cozy
    environment:
      COZY_ADMIN_PASSWORD: ${COZY_ADMIN_PASSWORD}
      COZY_TLD: ${COZY_TLD}
    volumes:
      - ${STORAGE_DIRECTORY}:/usr/local/cozy-stack/storage
    ports:
      - 8082:8080
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    restart: unless-stopped
```
And the following `.env` file
```
# Force the cozy stack version
# see https://cloud.docker.com/swarm/vsellier/repository/docker/vsellier/easy-cozy/tags for all available versions
# Examples : 
COZY_STACK_VERSION=latest
# COZY_STACK_VERSION=2018M2S5

# The place to store the database content
DATABASE_DIRECTORY=/home/eric/easy-cozy/db

# The place to store the cozy's raw files
STORAGE_DIRECTORY=/home/eric/easy-cozy/storage

# The place to store the let's encrypt stuff
# ACME_DIRECTORY=/var/lib/acme

# The base domain used for the cozy cloud instances
COZY_TLD=cozy.xxx.fr

# The contact email used for let's encrypt
EMAIL=eric@xxx.fr

# The admin passphrase
COZY_ADMIN_PASSPHRASE='xxx'
```
I can initialize the database, I can see the site both through localip:8082 and cozy.mydomain.fr. But ...
When I try to create the instance I get "Bad passphrase"
`eric@vault:~/easy-cozy $ sudo ./create-instance.sh eric`
```
Creating instance eric.cozy.xxx.fr ...
Failed to create instance for domain eric.cozy.xxx.fr
Error: Forbidden: bad passphrase
Could not generate access to domain eric.cozy.xxx.fr
Forbidden: bad passphrase
No token found.
```
I have tried a huge number of turnarounds (such as creating a variable COZY_ADMIN_PASSWORD in addition to COZY_ADMIN_PASSPHRASE) but there is no way to create the instance.
I have the feeling that I am close to completing the install, but I can't get past this obstacle.
Got any clue ?
